modLoader="javafml"
loaderVersion="*"
license="MIT"
clientSideOnly = false
showAsResourcePack = false
showAsDataPack = false

[[mods]]
modId="tfthreadsafetyaddon"
version="${version}"
displayName="TwilightForest Thread Safety Addon (For 1.20.1)"
logoFile="assets/tfthreadsafetyaddon/icon.png"
authors="ishland, CoZooo"
description='''Makes twilight forest generation thread-safe and faster
Forked from ishland/TFThreadSafetyAddon'''

[[mixins]]
config="tfthreadsafetyaddon.mixins.json"

[[dependencies.tfthreadsafetyaddon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfthreadsafetyaddon]]
modId = "twilightforest"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
